version: "3"
services:
    app:
          build: .
          container_name: container-lottery-api
          command: bash -c "npm install && npm i -g @adonisjs/cli && adonis serve --dev"
          ports:
              - "3333:3333"
          volumes:
              - .:/usr/app
    db:
        build: ./database
        volumes:
            - "./database/db:/var/lib/mysql"
        restart: always
        ports:
          - "3306:3306"

        environment:
          - MYSQL_ROOT_PASSWORD:"lottery-api"
          - MYSQL_DATABASE:"lottery-api"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1
